[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.5"
solana-client = "2.1.13"
solana-program = "2.1.13"
solana-sdk = "2.1.13"
spl-associated-token-account = "6.0.0"
spl-associated-token-account-client = "2.0.0"
spl-token = "7.0.0"
